version: '2'
services:
  slaughterhouse:
    privileged: true
    image: drpebcak/slaughterhouse:latest
    stdin_open: true
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    tty: true
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'
