version: '2'
services:
  slaughterhouse:
    image: tayworm/slaughterhouse:1
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
